export const USER_REGISTER_ACTION = 'app/App/USER_REGISTER_ACTION';
export const USER_REGISTER_SUCCESS_ACTION = 'app/App/USER_REGISTER_SUCCESS_ACTION';
export const USER_REGISTER_FAIL_ACTION = 'app/App/USER_REGISTER_FAIL_ACTION';

export const SEND_CODE_ACTION = 'app/App/SEND_CODE_ACTION';
export const SEND_CODE_SUCCESS_ACTION = 'app/App/SEND_CODE_SUCCESS_ACTION';
export const SEND_CODE_FAIL_ACTION = 'app/App/SEND_CODE_FAIL_ACTION';

export const GET_USER_INFO_ACTION = 'app/App/GET_USER_INFO_ACTION';
export const GET_USER_INFO_SUCCESS_ACTION = 'app/App/GET_USER_INFO_SUCCESS_ACTION';
export const GET_USER_INFO_FAIL_ACTION = 'app/App/GET_USER_INFO_FAIL_ACTION';

export const REPORT_USER_ACTION = 'app/App/REPORT_USER_ACTION';
export const REPORT_USER_SUCCESS_ACTION = 'app/App/REPORT_USER_SUCCESS_ACTION';
export const REPORT_USER_FAIL_ACTION = 'app/App/REPORT_USER_FAIL_ACTION';

export const CHANGE_PROFILE_ACTION = 'app/App/CHANGE_PROFILE_ACTION';
export const CHANGE_PROFILE_SUCCESS_ACTION = 'app/App/CHANGE_PROFILE_SUCCESS_ACTION';
export const CHANGE_PROFILE_FAIL_ACTION = 'app/App/CHANGE_PROFILE_FAIL_ACTION';

export const CHANGE_USER_PHOTO_ACTION = 'app/App/CHANGE_USER_PHOTO_ACTION';
export const CHANGE_USER_PHOTO_SUCCESS_ACTION = 'app/App/CHANGE_USER_PHOTO_SUCCESS_ACTION';
export const CHANGE_USER_PHOTO_FAIL_ACTION = 'app/App/CHANGE_USER_PHOTO_FAIL_ACTION';

export const GET_TWITS_ACTION = 'app/App/GET_TWITS_ACTION';
export const GET_TWITS_SUCCESS_ACTION = 'app/App/GET_TWITS_SUCCESS_ACTION';
export const GET_TWITS_FAIL_ACTION = 'app/App/GET_TWITS_FAIL_ACTION';

export const SEARCH_TWIT_ACTION = 'app/App/SEARCH_TWIT_ACTION';
export const SEARCH_TWIT_SUCCESS_ACTION = 'app/App/SEARCH_TWIT_SUCCESS_ACTION';
export const SEARCH_TWIT_FAIL_ACTION = 'app/App/SEARCH_TWIT_FAIL_ACTION';

export const CREATE_TWIT_ACTION = 'app/App/CREATE_TWIT_ACTION';
export const CREATE_TWIT_SUCCESS_ACTION = 'app/App/CREATE_TWIT_SUCCESS_ACTION';
export const CREATE_TWIT_FAIL_ACTION = 'app/App/CREATE_TWIT_FAIL_ACTION';

export const LIKE_TWIT_ACTION = 'app/App/LIKE_TWIT_ACTION';
export const LIKE_TWIT_SUCCESS_ACTION = 'app/App/LIKE_TWIT_SUCCESS_ACTION';
export const LIKE_TWIT_FAIL_ACTION = 'app/App/LIKE_TWIT_FAIL_ACTION';

export const UNLIKE_TWIT_ACTION = 'app/App/LUNIKE_TWIT_ACTION';
export const UNLIKE_TWIT_SUCCESS_ACTION = 'app/App/UNLIKE_TWIT_SUCCESS_ACTION';
export const UNLIKE_TWIT_FAIL_ACTION = 'app/App/UNLIKE_TWIT_FAIL_ACTION';

export const RETWIT_TWIT_ACTION = 'app/App/RETWIT_TWIT_ACTION';
export const RETWIT_TWIT_SUCCESS_ACTION = 'app/App/RETWIT_TWIT_SUCCESS_ACTION';
export const RETWIT_TWIT_FAIL_ACTION = 'app/App/RETWIT_TWIT_FAIL_ACTION';

export const UNRETWIT_TWIT_ACTION = 'app/App/UNRETWIT_TWIT_ACTION';
export const UNRETWIT_TWIT_SUCCESS_ACTION = 'app/App/UNRETWIT_TWIT_SUCCESS_ACTION';
export const UNRETWIT_TWIT_FAIL_ACTION = 'app/App/UNRETWIT_TWIT_FAIL_ACTION';

export const GET_REPORT_TWIT_TYPES_ACTION = 'app/App/GET_REPORT_TWIT_TYPES_ACTION';
export const GET_REPORT_TWIT_TYPES_SUCCESS_ACTION = 'app/App/GET_REPORT_TWIT_TYPES_SUCCESS_ACTION';
export const GET_REPORT_TWIT_TYPES_FAIL_ACTION = 'app/App/GET_REPORT_TWIT_TYPES_FAIL_ACTION';

export const REPORT_TWIT_ACTION = 'app/App/REPORT_TWIT_ACTION';
export const REPORT_TWIT_SUCCESS_ACTION = 'app/App/REPORT_TWIT_SUCCESS_ACTION';
export const REPORT_TWIT_FAIL_ACTION = 'app/App/REPORT_TWIT_FAIL_ACTION';

export const GET_COMMENTS_ACTION = 'app/App/GET_COMMENTS_ACTION';
export const GET_COMMENTS_SUCCESS_ACTION = 'app/App/GET_COMMENTS_SUCCESS_ACTION';
export const GET_COMMENTS_FAIL_ACTION = 'app/App/GET_COMMENTS_FAIL_ACTION';

export const CREATE_COMMENT_ACTION = 'app/App/CREATE_COMMENT_ACTION';
export const CREATE_COMMENT_SUCCESS_ACTION = 'app/App/CREATE_COMMENT_SUCCESS_ACTION';
export const CREATE_COMMENT_FAIL_ACTION = 'app/App/CREATE_COMMENT_FAIL_ACTION';

export const LIKE_COMMENT_ACTION = 'app/App/LIKE_COMMENT_ACTION';
export const LIKE_COMMENT_SUCCESS_ACTION = 'app/App/LIKE_COMMENT_SUCCESS_ACTION';
export const LIKE_COMMENT_FAIL_ACTION = 'app/App/LIKE_COMMENT_FAIL_ACTION';

export const UNLIKE_COMMENT_ACTION = 'app/App/UNLIKE_COMMENT_ACTION';
export const UNLIKE_COMMENT_SUCCESS_ACTION = 'app/App/UNLIKE_COMMENT_SUCCESS_ACTION';
export const UNLIKE_COMMENT_FAIL_ACTION = 'app/App/UNLIKE_COMMENT_FAIL_ACTION';

export const RETWIT_COMMENT_ACTION = 'app/App/RETWIT_COMMENT_ACTION';
export const RETWIT_COMMENT_SUCCESS_ACTION = 'app/App/RETWIT_COMMENT_SUCCESS_ACTION';
export const RETWIT_COMMENT_FAIL_ACTION = 'app/App/RETWIT_COMMENT_FAIL_ACTION';

export const UNRETWIT_COMMENT_ACTION = 'app/App/UNRETWIT_COMMENT_ACTION';
export const UNRETWIT_COMMENT_SUCCESS_ACTION = 'app/App/UNRETWIT_COMMENT_SUCCESS_ACTION';
export const UNRETWIT_COMMENT_FAIL_ACTION = 'app/App/UNRETWIT_COMMENT_FAIL_ACTION';

export const REPORT_COMMENT_ACTION = 'app/App/REPORT_COMMENT_ACTION';
export const REPORT_COMMENT_SUCCESS_ACTION = 'app/App/REPORT_COMMENT_SUCCESS_ACTION';
export const REPORT_COMMENT_FAIL_ACTION = 'app/App/REPORT_COMMENT_FAIL_ACTION';
